Extend iATS Payments Verification scheduled Jobs Log
iATSPayments/com.iatspayments.civicrm pull request #427
Opened 2023-08-11 11:26 UTC by yurg

Extend iATS Payments Verification scheduled Jobs Log by adding contribution/recurring contribution ID.

2023-09-26 21:44 UTC, adixon requested changes

2023-09-26 21:44 UTC, adixon commented on api/v3/Job/Iatsverify.php
> +  $message .= '<br />' . ts('Recurring Contribution ID: ') . !empty($contribution['contribution_recur_id'])?? $contribution['contribution_recur_id'];
This isn't the right place for this, you want it further up (this code will execute after looping through all the contributions, so at best you'd only see the last one).

2023-11-02 12:22 UTC, yurg commented
Thank you for review @adixon , a message moved inside the loop.

2024-05-16 15:29 UTC, adixon commented
Just reviewing this one again and thinking about it. The $message value will get really big for some sites and potentially start breaking things, so I'm not convinced this is a good idea. I wonder if there's a better solution to what you're trying to solve here in terms of providing some kind of logging.

2024-05-16 15:29 UTC, closed without merging